#ifndef MODBUS_HPP
#define MODBUS_HPP

#include <cstdint>

enum class ModbusFunctionCode : uint8_t {
    READ_DISCRETE_INPUTS = 2,
    READ_HOLDING_REGISTERS = 3,
    READ_INPUT_REGISTERS = 4,
    WRITE_SINGLE_COIL = 5,
    WRITE_SINGLE_REGISTER = 6,
    READ_EXCEPTION_STATUS = 7,
    DIAGNOSTIC_RETURN_READ_DATA = 8,
    WRITE_MULTIPLE_COILS = 15,
    WRITE_MULTIPLE_REGISTERS = 16,
    READ_HOLDING_REGISTER_AREA = 17,
    READ_INPUT_REGISTER_AREA = 18,
    FORCE_SINGLE_COIL = 21,
    PRESET_SINGLE_REGISTER = 22,
    READ_MULTIPLE_HOLDING_REGISTERS = 27,
    READ_MULTIPLE_INPUT_REGISTERS = 28,
    WRITE_MULTIPLE_HOLDING_REGISTERS = 30,
    WRITE_MULTIPLE_INPUT_REGISTERS = 31,
    REPORT_SLAVE_DATA = 43,
};

#endif
